### ISSUE TITLE
Flavor/MAA Discussion

### ISSUE THREAD

**Issue by dragoon-103** [leon123442/AsiaExpansionProject#4]

**Comment by Eisprinzessin** [comment]
![Mongolian_Mangudai](https://user-images.githubusercontent.com/72768108/150620512-1cb40148-955b-4099-998c-4de079316475.jpg)
 adding later Mangudai Stronger mongolic horse archers

**Comment by Eisprinzessin** [comment]
![kithan_have_cav_2](https://user-images.githubusercontent.com/72768108/150620536-56fd33b2-cce9-4394-8d11-b3ccbd70fd64.jpg)
 adding later Kithan Heavy Cav.
